import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Code2, 
  Download, 
  Copy, 
  Check, 
  FileText, 
  Settings, 
  Play, 
  RefreshCw, 
  Shield, 
  DollarSign,
  Zap,
  AlertTriangle,
  CheckCircle
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { useInfrastructure } from '@/contexts/InfrastructureContext';
import { toast } from 'sonner';
import type { IaCFramework, InfraNode, InfraEdge } from '@/types/infrastructure';
import type { EnhancedIaCOutput, IaCGenerationOptions } from '@/types/extended';

interface IaCGeneratorProps {
  nodes: InfraNode[];
  edges: InfraEdge[];
  framework: IaCFramework;
  onFrameworkChange: (framework: IaCFramework) => void;
}

const frameworkIcons = {
  terraform: '🌍',
  cloudformation: '☁️',
  pulumi: '🔷',
};

const frameworkColors = {
  terraform: 'bg-purple-500',
  cloudformation: 'bg-orange-500',
  pulumi: 'bg-blue-500',
};

export function IaCGenerator({ nodes, edges, framework, onFrameworkChange }: IaCGeneratorProps) {
  const [generatedCode, setGeneratedCode] = useState('');
  const [enhancedOutput, setEnhancedOutput] = useState<EnhancedIaCOutput | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [options, setOptions] = useState<IaCGenerationOptions>({
    framework,
    provider: 'aws',
    region: 'us-east-1',
    include_comments: true,
    security_best_practices: true,
    cost_optimization: true,
  });

  useEffect(() => {
    if (nodes.length > 0) {
      generateIaC();
    }
  }, [nodes, edges, framework, options]);

  const generateIaC = useCallback(async () => {
    if (nodes.length === 0) return;

    setIsGenerating(true);
    try {
      // Simulate IaC generation with AI
      await new Promise(resolve => setTimeout(resolve, 1500));

      const output = await generateEnhancedIaC(nodes, edges, options);
      setEnhancedOutput(output);
      setGeneratedCode(output.code);
    } catch (error) {
      toast.error('Failed to generate IaC code');
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  }, [nodes, edges, options]);

  const generateEnhancedIaC = async (
    nodes: InfraNode[], 
    edges: InfraEdge[], 
    opts: IaCGenerationOptions
  ): Promise<EnhancedIaCOutput> => {
    const baseOutput = generateBaseIaC(nodes, edges, opts);
    
    // Add security recommendations
    const securityRecommendations = generateSecurityRecommendations(nodes, opts);
    
    // Add cost estimates
    const costEstimates = generateCostEstimates(nodes);
    
    // Add compliance checks
    const complianceChecks = generateComplianceChecks(nodes, opts);

    return {
      ...baseOutput,
      security_recommendations: securityRecommendations,
      cost_estimates: costEstimates,
      compliance_checks: complianceChecks,
    };
  };

  const generateBaseIaC = (nodes: InfraNode[], edges: InfraEdge[], opts: IaCGenerationOptions) => {
    const files: { name: string; content: string }[] = [];
    
    if (opts.framework === 'terraform') {
      files.push({
        name: 'main.tf',
        content: generateTerraformCode(nodes, edges, opts),
      });
      files.push({
        name: 'variables.tf',
        content: generateTerraformVariables(nodes),
      });
      files.push({
        name: 'outputs.tf',
        content: generateTerraformOutputs(nodes),
      });
    } else if (opts.framework === 'cloudformation') {
      files.push({
        name: 'template.yaml',
        content: generateCloudFormationCode(nodes, edges, opts),
      });
    } else if (opts.framework === 'pulumi') {
      files.push({
        name: 'index.ts',
        content: generatePulumiCode(nodes, edges, opts),
      });
    }

    return {
      framework: opts.framework,
      code: files[0]?.content || '',
      files,
    };
  };

  const generateTerraformCode = (nodes: InfraNode[], edges: InfraEdge[], opts: IaCGenerationOptions) => {
    let code = `# Generated by InfraViz AI - ${new Date().toISOString()}\n`;
    code += `# Provider configuration\n`;
    code += `provider "aws" {\n`;
    code += `  region = "${opts.region}"\n`;
    code += `}\n\n`;

    // Group resources by type
    const resourcesByType = nodes.reduce((acc, node) => {
      acc[node.type] = acc[node.type] || [];
      acc[node.type].push(node);
      return acc;
    }, {} as Record<string, InfraNode[]>);

    // Generate resources
    Object.entries(resourcesByType).forEach(([type, resources]) => {
      resources.forEach((resource, index) => {
        const resourceName = `${type.replace('-', '_')}_${index}`;
        code += generateTerraformResource(resourceName, resource, opts);
      });
    });

    return code;
  };

  const generateTerraformResource = (name: string, resource: InfraNode, opts: IaCGenerationOptions) => {
    let code = `resource "aws_${resource.type.replace('-', '_')}" "${name}" {\n`;
    
    // Add properties
    Object.entries(resource.properties).forEach(([key, value]) => {
      if (opts.include_comments) {
        code += `  # ${key}\n`;
      }
      if (typeof value === 'boolean') {
        code += `  ${key} = ${value}\n`;
      } else if (typeof value === 'number') {
        code += `  ${key} = ${value}\n`;
      } else if (Array.isArray(value)) {
        code += `  ${key} = ${JSON.stringify(value)}\n`;
      } else {
        code += `  ${key} = "${value}"\n`;
      }
    });

    // Add security best practices
    if (opts.security_best_practices) {
      code += generateSecurityBestPractices(resource.type);
    }

    // Add tags
    code += `  tags = {\n`;
    code += `    Name = "${resource.label}"\n`;
    code += `    Environment = "production"\n`;
    code += `    ManagedBy = "infra-viz-ai"\n`;
    if (opts.cost_optimization) {
      code += `    CostOptimized = "true"\n`;
    }
    code += `  }\n`;
    code += `}\n\n`;

    return code;
  };

  const generateSecurityBestPractices = (resourceType: string) => {
    const practices: Record<string, string> = '';
    
    switch (resourceType) {
      case 's3':
        return `  # Security best practices\n  versioning {\n    enabled = true\n  }\n  server_side_encryption_configuration {\n    rule {\n      apply_server_side_encryption_by_default {\n        sse_algorithm = "AES256"\n      }\n    }\n  }\n  public_access_block {\n    block_public_acls   = true\n    block_public_policy = true\n    ignore_public_acls  = true\n    restrict_public_buckets = true\n  }\n`;
      case 'rds':
        return `  # Security best practices\n  storage_encrypted = true\n  skip_final_snapshot = false\n  backup_retention_period = 7\n  deletion_protection = true\n`;
      case 'ec2':
        return `  # Security best practices\n  monitoring = true\n  ebs_optimized = true\n`;
      default:
        return '';
    }
  };

  const generateCloudFormationCode = (nodes: InfraNode[], edges: InfraEdge[], opts: IaCGenerationOptions) => {
    let yaml = `AWSTemplateFormatVersion: '2010-09-09'\n`;
    yaml += `Description: Generated by InfraViz AI - ${new Date().toISOString()}\n\n`;
    
    yaml += `Parameters:\n`;
    yaml += `  Environment:\n`;
    yaml += `    Type: String\n`;
    yaml += `    Default: production\n`;
    yaml += `    Description: Environment name\n\n`;

    yaml += `Resources:\n`;
    
    nodes.forEach((node, index) => {
      const logicalId = `${node.type.charAt(0).toUpperCase() + node.type.slice(1)}${index}`;
      yaml += `  ${logicalId}:\n`;
      yaml += `    Type: AWS::${node.type.toUpperCase().replace('-', '::')}\n`;
      yaml += `    Properties:\n`;
      
      Object.entries(node.properties).forEach(([key, value]) => {
        if (typeof value === 'boolean') {
          yaml += `      ${key}: ${value}\n`;
        } else if (typeof value === 'number') {
          yaml += `      ${key}: ${value}\n`;
        } else {
          yaml += `      ${key}: "${value}"\n`;
        }
      });
      
      yaml += `      Tags:\n`;
      yaml += `        - Key: Name\n`;
      yaml += `          Value: ${node.label}\n`;
      yaml += `        - Key: Environment\n`;
      yaml += `          Value: !Ref Environment\n`;
      yaml += `        - Key: ManagedBy\n`;
      yaml += `          Value: infra-viz-ai\n`;
      yaml += `\n`;
    });

    return yaml;
  };

  const generatePulumiCode = (nodes: InfraNode[], edges: InfraEdge[], opts: IaCGenerationOptions) => {
    let code = `import * as pulumi from "@pulumi/pulumi";\n`;
    code += `import * as aws from "@pulumi/aws";\n\n`;
    code += `// Generated by InfraViz AI - ${new Date().toISOString()}\n\n`;

    nodes.forEach((node, index) => {
      const resourceName = `${node.type.replace('-', '')}${index}`;
      code += `const ${resourceName} = new aws.${node.type.replace('-', '.')}("${resourceName}", {\n`;
      
      Object.entries(node.properties).forEach(([key, value]) => {
        if (typeof value === 'boolean' || typeof value === 'number') {
          code += `  ${key}: ${value},\n`;
        } else {
          code += `  ${key}: "${value}",\n`;
        }
      });
      
      code += `  tags: {\n`;
      code += `    Name: "${node.label}",\n`;
      code += `    Environment: "production",\n`;
      code += `    ManagedBy: "infra-viz-ai",\n`;
      code += `  },\n`;
      code += `});\n\n`;
    });

    return code;
  };

  const generateTerraformVariables = (nodes: InfraNode[]) => {
    let code = `variable "region" {\n`;
    code += `  description = "AWS region"\n`;
    code += `  type        = string\n`;
    code += `  default     = "us-east-1"\n`;
    code += `}\n\n`;

    code += `variable "environment" {\n`;
    code += `  description = "Environment name"\n`;
    code += `  type        = string\n`;
    code += `  default     = "production"\n`;
    code += `}\n\n`;

    return code;
  };

  const generateTerraformOutputs = (nodes: InfraNode[]) => {
    let code = '';
    
    nodes.forEach((node, index) => {
      const resourceName = `${node.type.replace('-', '_')}_${index}`;
      code += `output "${resourceName}_id" {\n`;
      code += `  description = "ID of ${node.label}"\n`;
      code += `  value       = aws_${node.type.replace('-', '_')}.${resourceName}.id\n`;
      code += `}\n\n`;
    });

    return code;
  };

  const generateSecurityRecommendations = (nodes: InfraNode[], opts: IaCGenerationOptions) => {
    const recommendations: string[] = [];
    
    nodes.forEach(node => {
      switch (node.type) {
        case 's3':
          recommendations.push('Enable S3 bucket versioning for data protection');
          recommendations.push('Configure S3 bucket encryption at rest');
          recommendations.push('Block public access to S3 bucket');
          break;
        case 'rds':
          recommendations.push('Enable RDS encryption at rest');
          recommendations.push('Configure RDS backup and retention');
          recommendations.push('Enable RDS enhanced monitoring');
          break;
        case 'ec2':
          recommendations.push('Enable EC2 detailed monitoring');
          recommendations.push('Configure EC2 security groups properly');
          recommendations.push('Use EC2 instance profiles instead of access keys');
          break;
        case 'vpc':
          recommendations.push('Configure VPC flow logs');
          recommendations.push('Use private subnets for sensitive resources');
          break;
      }
    });

    return [...new Set(recommendations)]; // Remove duplicates
  };

  const generateCostEstimates = (nodes: InfraNode[]) => {
    const estimates: Record<string, number> = {};
    
    nodes.forEach(node => {
      const instanceType = node.properties.instanceType;
      let cost = 0;
      
      switch (node.type) {
        case 'ec2':
          const ec2Costs: Record<string, number> = {
            't3.micro': 7.59,
            't3.small': 15.18,
            't3.medium': 30.37,
            't3.large': 60.74,
            'm5.large': 70.08,
          };
          cost = ec2Costs[instanceType] || 50;
          break;
        case 'rds':
          const rdsCosts: Record<string, number> = {
            'db.t3.micro': 12.41,
            'db.t3.small': 24.82,
            'db.t3.medium': 49.64,
          };
          cost = rdsCosts[instanceType] || 100;
          break;
        case 's3':
          cost = 23; // Standard storage cost per month
          break;
        case 'lambda':
          cost = 0; // Lambda has per-request pricing
          break;
        default:
          cost = 10; // Default estimate
      }
      
      estimates[node.label] = cost;
    });

    return estimates;
  };

  const generateComplianceChecks = (nodes: InfraNode[], opts: IaCGenerationOptions) => {
    return {
      iso27001: nodes.length > 0 ? 85 : 0, // Basic compliance score
      gdpr: nodes.some(n => n.type === 'rds') ? 90 : 70,
      hipaa: nodes.some(n => n.type === 'rds') ? 85 : 60,
    };
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generatedCode);
      setCopied(true);
      toast.success('Code copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast.error('Failed to copy code');
    }
  };

  const handleDownload = () => {
    if (!enhancedOutput) return;

    enhancedOutput.files.forEach(file => {
      const blob = new Blob([file.content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = file.name;
      link.click();
      URL.revokeObjectURL(url);
    });

    toast.success('IaC files downloaded');
  };

  const handleValidate = () => {
    // Mock validation
    toast.success('IaC code validation passed');
  };

  return (
    <div className="space-y-6">
      {/* Controls */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className={`p-2 rounded-lg ${frameworkColors[framework]}/10`}>
                <span className="text-lg">{frameworkIcons[framework]}</span>
              </div>
              <div>
                <CardTitle className="flex items-center gap-2">
                  IaC Code Generator
                  <Badge variant="secondary">{framework.toUpperCase()}</Badge>
                </CardTitle>
                <CardDescription>
                  Generate production-ready Infrastructure as Code
                </CardDescription>
              </div>
            </div>
            <div className="flex gap-2">
              <Select value={framework} onValueChange={onFrameworkChange}>
                <SelectTrigger className="w-40">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="terraform">🌍 Terraform</SelectItem>
                  <SelectItem value="cloudformation">☁️ CloudFormation</SelectItem>
                  <SelectItem value="pulumi">🔷 Pulumi</SelectItem>
                </SelectContent>
              </Select>
              <Button variant="outline" onClick={generateIaC} disabled={isGenerating}>
                {isGenerating ? (
                  <RefreshCw className="h-4 w-4 animate-spin" />
                ) : (
                  <RefreshCw className="h-4 w-4" />
                )}
              </Button>
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Options */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Generation Options</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id="comments"
                checked={options.include_comments}
                onChange={(e) => setOptions({ ...options, include_comments: e.target.checked })}
                className="rounded"
              />
              <label htmlFor="comments" className="text-sm">Include Comments</label>
            </div>
            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id="security"
                checked={options.security_best_practices}
                onChange={(e) => setOptions({ ...options, security_best_practices: e.target.checked })}
                className="rounded"
              />
              <label htmlFor="security" className="text-sm">Security Best Practices</label>
            </div>
            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id="cost"
                checked={options.cost_optimization}
                onChange={(e) => setOptions({ ...options, cost_optimization: e.target.checked })}
                className="rounded"
              />
              <label htmlFor="cost" className="text-sm">Cost Optimization</label>
            </div>
            <div className="flex items-center space-x-2">
              <label htmlFor="region" className="text-sm">Region:</label>
              <Select value={options.region} onValueChange={(value) => setOptions({ ...options, region: value })}>
                <SelectTrigger className="w-24">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="us-east-1">us-east-1</SelectItem>
                  <SelectItem value="us-west-2">us-west-2</SelectItem>
                  <SelectItem value="eu-west-1">eu-west-1</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Generated Code */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle className="text-lg">Generated Code</CardTitle>
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={handleValidate}>
                    <CheckCircle className="h-4 w-4 mr-2" />
                    Validate
                  </Button>
                  <Button variant="outline" size="sm" onClick={handleCopy}>
                    {copied ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                    {copied ? 'Copied' : 'Copy'}
                  </Button>
                  <Button variant="outline" size="sm" onClick={handleDownload}>
                    <Download className="h-4 w-4 mr-2" />
                    Download
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <AnimatePresence>
                {isGenerating ? (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="flex items-center justify-center py-12"
                  >
                    <div className="text-center">
                      <RefreshCw className="h-8 w-8 animate-spin mx-auto mb-4 text-primary" />
                      <p className="text-muted-foreground">Generating IaC code...</p>
                    </div>
                  </motion.div>
                ) : (
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -20 }}
                  >
                    <ScrollArea className="h-[500px] w-full rounded-md border">
                      <pre className="p-4 text-sm font-mono whitespace-pre-wrap">
                        <code>{generatedCode}</code>
                      </pre>
                    </ScrollArea>
                  </motion.div>
                )}
              </AnimatePresence>
            </CardContent>
          </Card>
        </div>

        {/* Sidebar */}
        <div className="space-y-4">
          {/* Security Recommendations */}
          {enhancedOutput?.security_recommendations && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg flex items-center gap-2">
                  <Shield className="h-5 w-5" />
                  Security
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {enhancedOutput.security_recommendations.slice(0, 3).map((rec, index) => (
                    <div key={index} className="flex items-start gap-2 text-sm">
                      <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 flex-shrink-0" />
                      {rec}
                    </div>
                  ))}
                  {enhancedOutput.security_recommendations.length > 3 && (
                    <p className="text-xs text-muted-foreground">
                      +{enhancedOutput.security_recommendations.length - 3} more
                    </p>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Cost Estimates */}
          {enhancedOutput?.cost_estimates && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg flex items-center gap-2">
                  <DollarSign className="h-5 w-5" />
                  Cost Estimates
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {Object.entries(enhancedOutput.cost_estimates).slice(0, 3).map(([resource, cost]) => (
                    <div key={resource} className="flex justify-between text-sm">
                      <span className="text-muted-foreground">{resource}</span>
                      <span className="font-medium">${cost}/mo</span>
                    </div>
                  ))}
                  <div className="pt-2 border-t">
                    <div className="flex justify-between font-medium">
                      <span>Total</span>
                      <span>${Object.values(enhancedOutput.cost_estimates).reduce((a, b) => a + b, 0)}/mo</span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Compliance */}
          {enhancedOutput?.compliance_checks && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg flex items-center gap-2">
                  <FileText className="h-5 w-5" />
                  Compliance
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {Object.entries(enhancedOutput.compliance_checks).map(([standard, score]) => (
                    <div key={standard} className="space-y-1">
                      <div className="flex justify-between text-sm">
                        <span className="uppercase">{standard}</span>
                        <span className="font-medium">{score}%</span>
                      </div>
                      <div className="w-full bg-gray-200 rounded-full h-2">
                        <div
                          className={`h-2 rounded-full ${
                            score >= 90 ? 'bg-green-500' : score >= 70 ? 'bg-yellow-500' : 'bg-red-500'
                          }`}
                          style={{ width: `${score}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}
